
LEFT_SHOE_FORCE = "LEFT_SHOE_FORCE"
LEFT_SHOE_ACCELERATION = "LEFT_SHOE_ACCELERATION"
LEFT_SHOE_ROTATION = "LEFT_SHOE_ROTATION"
LEFT_SHOE_ORIENTATION = "LEFT_SHOE_ORIENTATION"
LEFT_SHOE_TEMPERATURE = "LEFT_SHOE_ORIENTATION"
