
LEFT_PERIPHERAL_UUID = "E8:39:E4:37:0E:27"  #Boogio_L
RIGHT_PERIPHERAL_UUID = "D3:B9:66:45:F9:9F"  #Boogio_R

CSV_LOG_DIRECTORY = '/home/pi/Desktop/Logs/Boogio5/'

MAX_FORCE_VALUE = 1023.0
MAX_ACCELERATION_VALUE = 8000.0
MAX_ROTATION_VALUE = 1000.0
MAX_ORIENTATION_VALUE = 4800.0
MAX_SHORT_VALUE = 65535.0
HALF_OF_MAX_SHORT_VALUE = 32767.0


ACCELERATION_CONVERSION_COEFFICIENT = MAX_ACCELERATION_VALUE / HALF_OF_MAX_SHORT_VALUE
ROTATION_CONVERSION_COEFFICIENT = MAX_ROTATION_VALUE / HALF_OF_MAX_SHORT_VALUE
ORIENTATION_CONVERSION_COEFFICIENT = MAX_ORIENTATION_VALUE / HALF_OF_MAX_SHORT_VALUE 
